### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by braaar** [braaar/jam-assistant#10]
A navigation in the header would be nice when we have multiple pages to navigate between. 

I suggest we use [React Router](https://reactrouter.com/docs/en/v6/getting-started/tutorial) for navigation

- [ ] Install React Router
- [ ] Set up Routing
- [ ] Add route for `jam.tsx` at `/` (root of the web page)
- [ ] Add navigation link to `/` (using React Router's `Link` Element)

**Comment by NehaK275** [comment]
Hi @braaar can i solve this?

**Comment by braaar** [comment]
> Hi @braaar can i solve this?

Sure! you could start out by [installing React Router](https://reactrouter.com/docs/en/v6/getting-started/installation) (remember to use `yarn`, not `npm`) and setting up Routes. Right now we only have one page `jam.tsx`, but it's still worthwhile to set up the Routing stuff and a simple navigation link in the header (which just points to the home page). 

When it's all set up that makes it easy to add new routes in the future when we add more pages.

Are you familiar with React and React Router? It's fairly simple stuff, but if it's new to you I would recommend that you tinker around with it a little in local development to see how it works.

**Comment by kashyap010** [comment]
@braaar Has this issue been resolved? The about page component exists but react router has not been set up. 
I can learn react router and try to implement it for this project.

**Comment by braaar** [comment]
completed in #10
