### ISSUE TITLE
Add links/content to footer

### ISSUE THREAD

**Issue by braaar** [braaar/jam-assistant#11]
- [ ] Link to this github repository
- [ ] License info?

**Comment by braaar** [comment]
I think a link to the github repository would be a nice start. Perhaps we could remove the silly "Footer" heading and just put a centered `<a>` tag in the footer with a link to the repository.

**Comment by kashyap010** [comment]
Hey @braaar 

I have implemented your suggestions in pr #34

**Comment by braaar** [comment]
Thanks, @kashyap010!
