### ISSUE TITLE
App always shows Am by default

### ISSUE THREAD

**Issue by braaar** [braaar/jam-assistant#16]
When I load the page it's always showing `Am` in the chord list. 

We need to remove that as a default value from the useState:
https://github.com/braaar/jam-assistant/blob/7add1fe24eb47144050b88a59378f9227817d038/src/jam.tsx#L7

**Comment by RishiKumarRay** [comment]
when we remove it will automatically update ?right?

**Comment by braaar** [comment]
> when we remove it will automatically update ?right?

Hello there! Welcome to this project. You're the first external contributor so far! 

Yes, I have set up a github action so that when we push the changes to main, the app will deploy to github pages with the new changes automatically.

This value should default to an empty array, `[]`

Wanna make a Pull Request for this?

**Comment by RishiKumarRay** [comment]
Yes i would love to make a PR

**Comment by RishiKumarRay** [comment]
@braaar  please review
