### ISSUE TITLE
Update meta description

### ISSUE THREAD

**Issue by braaar** [braaar/jam-assistant#24]
We should update the description tag. Right now it says `Web site created using create-react-app`.

I would rather have it say something like `A web app you can use at a live jam session to come up with ideas.` (we can work on the description more, but it's a start).

https://github.com/braaar/jam-assistant/blob/95cb0dd37378bfed9226d309ef8a614491f08b7d/public/index.html#L9

**Comment by NaincyKumariKnoldus** [comment]
Hey @braaar  I have updated this meta description. Please review my PR! Thanks

**Comment by NaincyKumariKnoldus** [comment]
fixes #24

**Comment by NaincyKumariKnoldus** [comment]
Hey @braaar I have added that in PR as per your wish.
